version: '3'

services:
  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - 6379:6379

  eureka:
    image: redbeandock/polyshop-discovery-server:latest
    ports:
      - "8761:8761"

  rabbitmq:
    image: rabbitmq:management
    ports:
      - "5672:5672"
      - "15672:15672"
